// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp4GNkO1Cy9j6MmQNZdAAOCAUBld1gULc',
    appId: '1:256981910956:web:d1046efc72677a83eb6609',
    messagingSenderId: '256981910956',
    projectId: 'learning-dart-43c90',
    authDomain: 'learning-dart-43c90.firebaseapp.com',
    storageBucket: 'learning-dart-43c90.appspot.com',
    measurementId: 'G-1FDS2FHWK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7AFDd-3umkTFahqM483sU0FLBmtU4zUQ',
    appId: '1:256981910956:android:e00640eeab5cb276eb6609',
    messagingSenderId: '256981910956',
    projectId: 'learning-dart-43c90',
    storageBucket: 'learning-dart-43c90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtt6QKaOhFTGaP0vqGUB2Rm-vt61YzMz4',
    appId: '1:256981910956:ios:22db2cbfb4f309f9eb6609',
    messagingSenderId: '256981910956',
    projectId: 'learning-dart-43c90',
    storageBucket: 'learning-dart-43c90.appspot.com',
    iosClientId: '256981910956-2gv8km17nh0q7mvlqqahaj7ake7jol0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtt6QKaOhFTGaP0vqGUB2Rm-vt61YzMz4',
    appId: '1:256981910956:ios:24c2e418bc9aadd6eb6609',
    messagingSenderId: '256981910956',
    projectId: 'learning-dart-43c90',
    storageBucket: 'learning-dart-43c90.appspot.com',
    iosClientId: '256981910956-8di48c21m8h1hr6ukid5l1l711neb6t0.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart.RunnerTests',
  );
}
